DELETE FROM MANAFACTURER;
INSERT INTO MANAFACTURER (ID, COMPANY, CREATED_AT)
VALUES(1, 'ASUS', TO_DATE('14.12.2021.', 'DD.MM.YYYY.'));
INSERT INTO MANAFACTURER (ID, COMPANY, CREATED_AT)
VALUES(2, 'MSI', TO_DATE('14.12.2021.', 'DD.MM.YYYY.'));


DELETE FROM COMPONENT;
INSERT INTO COMPONENT (ID, TITLE, DESCRIPTION,MANAFACTURER_ID,  TYPE ,CREATED_AT)
VALUES(1, 'RTX 3070', 'GAMER GPU', 1, 'GPU',TO_DATE('14.11.2021.', 'DD.MM.YYYY.'));
INSERT INTO COMPONENT (ID, TITLE, DESCRIPTION, MANAFACTURER_ID, TYPE ,CREATED_AT)
VALUES(2, 'RTX 3070 Ti', 'GAMER GPU', 2, 'GPU',TO_DATE('14.11.2021.', 'DD.MM.YYYY.'));


DELETE FROM USERS;
INSERT INTO USERS (USERNAME, PASSWORD, ENABLED)
VALUES ('admin', '$2a$10$ZJfRL79LpKhCWQYT3.07GOL/qjKN5SmRPa5ydI56cYCy/6QMgVLIy', 1);
INSERT INTO USERS (USERNAME, PASSWORD, ENABLED)
VALUES ('user', '$2a$10$c6iY8l6MJJvd/.kJ2FKHB.Jn6Ag/iwqzMyNri.ckXPm7uCbX9UHZu', 1);

DELETE FROM AUTHORITIES;
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY)
values ('admin', 'ROLE_ADMIN');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY)
values ('admin', 'ROLE_USER');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY)
values ('user', 'ROLE_USER');

